---
####################################################################
# Example :  Hitachi Universal Replicator (HUR) Playbook
####################################################################
- name: HUR
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars_files:
    - ansible_vault_storage_var.yml
  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"
      
  tasks:
  - name: Create a HUR pair in new copy group
    hitachivantara.vspone_block.vsp.hv_hur:
      state: "present"
      connection_info: "{{ connection_info }}"
      secondary_connection_info: "{{ secondary_connection_info }}"
      spec:
        copy_group_name: "Production"
        copy_pair_name: "Production_1"
        primary_volume_id: 8192
        secondary_pool_id: 1
        primary_volume_journal_id: 40
        secondary_volume_journal_id: 40
        local_device_group_name: "Production_PVOL"
        remote_device_group_name: "Production_SVOL"
        consistency_group_id: 40
        secondary_hostgroup:
            name: "mySQL-HUR-Ansible"
            port: "CL1-A"
            lun_id: 0
        mirror_unit_id: 0
        is_data_reduction_force_copy: false
        path_group_id: 5
    register: result
  - name: Debug the result variable
    ansible.builtin.debug:
        var: result