---
####################################################################
# Example : Shadow Image Pair Playbook
####################################################################
- name: Shadow Image Pair Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    #########################################################################
    # Task Name : Create shadow image pair for non-existing secondary volume
    #########################################################################
    - name: Create shadow image pair for non-existing secondary volume
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          primary_volume_id: "{{ pvol_id }}"
          secondary_pool_id: "{{ secondary_pool_id }}"
          allocate_new_consistency_group: true
          consistency_group_id: 7
          copy_pace_track_size: "MEDIUM"
          enable_quick_mode: false
          auto_split: false
          copy_group_name: "{{si_cp_grp_name}}"
          copy_pair_name: "{{ si_cp_pair_name }}"
          primary_volume_device_group_name: "{{ si_pvol_dev_grp_name }}"
          secondary_volume_device_group_name: "{{ si_svol_dev_grp_name }}"
      register: result
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
    - name: Set si_svol_id for workflow
      set_stats:
        data:
          si_svol_id: "{{ result.data.secondary_volume_id }}"
      