---
####################################################################
# Example : Shadow Image Pair Playbook
####################################################################
- name: Shadow Image Pair Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_primary_storage_username }}"
      password: "{{ vault_primary_storage_secret }}"

  tasks:
    #########################################################################
    # Task Name : Create shadow image pair for non-existing secondary volume
    #########################################################################
    - name: Create shadow image pair for non-existing secondary volume
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          primary_volume_id: "{{ pvol_id }}"
          secondary_pool_id: "{{ secondary_pool_id }}"
          allocate_new_consistency_group: true
          copy_pace_track_size: "MEDIUM"
          enable_quick_mode: false
          auto_split: true
          si_copy_group_name: "{{si_cp_grp_name}}"
          si_copy_pair_name: "{{ si_cp_pair_name }}"
          si_primary_volume_device_group_name: "{{ si_pvol_dev_grp_name }}"
          si_secondary_volume_device_group_name: "{{ si_svol_dev_grp_name }}"
      register: result