---
####################################################################
# Example : Shadow Image Pair Playbook
####################################################################
- name: Shadow Image Pair Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ####################################################################
    # Task Name : Split shadow image pair
    ####################################################################
    - name: Split shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        state: "split"
        spec:
          primary_volume_id: "{{pvol_id}}"
          secondary_volume_id: "{{ si_svol_id }}"
          enable_quick_mode: true
          enable_read_write: true
          copy_group_name: "{{si_cp_grp_name}}"
          copy_pair_name: "{{ si_cp_pair_name }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result